FROM microsoft/aspnetcore-build:1.0-2.0
WORKDIR /src

# caches restore result by copying csproj file separately
COPY ./RemoteRightClickServer/*.csproj .
RUN dotnet restore

# copies the rest of your code
COPY ./RemoteRightClickServer .
RUN dotnet publish --output /app/ --configuration Release

WORKDIR /app
EXPOSE 80
ENTRYPOINT ["dotnet", "RemoteRightClickServer.dll"]
